# version: "3.7" # Uncomment for older compose versions
services:
  poetry-project:
    container_name: poetry-project
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
